package io.haifa.agent.application.project.product.coding.delivery;

public enum CodingDeliveryEvidenceKind {
    WORKSPACE_CHANGE,
    DIFF_INSPECTION,
    VALIDATION_ATTEMPT,
    VALIDATION_PASSED,
    VALIDATION_FAILED,
    READ_ONLY_INSPECTION,
    NO_CHANGE_JUSTIFICATION,
    BLOCKER_CONFIRMED,
    STATUS_INSPECTED,
    REPOSITORY_ROOT_VERIFIED,
    BRANCH_VERIFIED,
    STAGED_DIFF_INSPECTED,
    STAGE_COMPLETED,
    COMMIT_COMPLETED,
    HEAD_VERIFIED,
    PUSH_COMPLETED,
    REMOTE_REF_VERIFIED,
    PULL_REQUEST_COMPLETED,
    PULL_REQUEST_VERIFIED
}
