package io.haifa.agent.application.project.tool.web;

public enum WebFailureCode {
    WEB_INVALID_REQUEST,
    WEB_UNSUPPORTED_OPTION,
    WEB_URL_DENIED,
    WEB_DNS_DENIED,
    WEB_PROVIDER_NOT_CONFIGURED,
    WEB_CREDENTIAL_MISSING,
    WEB_AUTH_FAILED,
    WEB_RATE_LIMITED,
    WEB_QUOTA_EXHAUSTED,
    WEB_TIMEOUT,
    WEB_CANCELLED,
    WEB_RESPONSE_TOO_LARGE,
    WEB_UNSUPPORTED_MEDIA_TYPE,
    WEB_PROVIDER_RESPONSE_INVALID,
    WEB_PROVIDER_FAILED
}
