#!/usr/bin/env python3
"""Generate the single Haifa Agent SQLite V1.0 initialization artifact."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REGISTRATION_PATTERN = re.compile(
    r'new RegisteredMigration\(\s*([0-9_]+),\s*"([^"]+)",\s*"([^"]+)"\s*\)',
    re.MULTILINE,
)
RESOURCE_PATTERN = re.compile(r"V([0-9]+)__.+\.sql")
HEADER = """-- Generated by build-support/scripts/generate_haifa_agent_v1_schema.py.
-- Do not edit this artifact directly; edit the canonical migration registry/resources.
PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;

CREATE TABLE IF NOT EXISTS schema_migration (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    checksum TEXT NOT NULL,
    applied_at INTEGER NOT NULL CHECK (applied_at >= 0)
);

"""


@dataclass(frozen=True)
class Migration:
    version: int
    name: str
    resource: str
    script: bytes

    @property
    def checksum(self) -> str:
        return "sha256:" + hashlib.sha256(self.script).hexdigest()


def repository_root() -> Path:
    return Path(__file__).resolve().parents[2]


def load_migrations(root: Path) -> tuple[list[Migration], Path]:
    source = root / (
        "haifa-agent-integrations/haifa-agent-store-sqlite/src/main/java/"
        "io/haifa/agent/store/sqlite/migration/HaifaAgentStoreMigrations.java"
    )
    resource_root = root / (
        "haifa-agent-integrations/haifa-agent-store-sqlite/src/main/resources/"
        "io/haifa/agent/store/sqlite/migration"
    )
    registrations = REGISTRATION_PATTERN.findall(source.read_text(encoding="utf-8"))
    if not registrations:
        raise ValueError(f"No migrations found in {source}")

    migrations: list[Migration] = []
    for raw_version, name, resource in registrations:
        path = resource_root / resource
        if not path.is_file():
            raise ValueError(f"Registered migration is missing: {path}")
        migrations.append(Migration(int(raw_version.replace("_", "")), name, resource, path.read_bytes()))

    versions = [migration.version for migration in migrations]
    names = [migration.name for migration in migrations]
    if versions != sorted(versions) or len(versions) != len(set(versions)) or len(names) != len(set(names)):
        raise ValueError("Migration versions must be ordered and versions/names must be unique")

    discovered = {
        path.name
        for path in resource_root.iterdir()
        if path.is_file() and RESOURCE_PATTERN.fullmatch(path.name)
    }
    registered = {migration.resource for migration in migrations}
    if discovered != registered:
        raise ValueError(
            "Registry/resource mismatch: "
            f"unregistered={sorted(discovered - registered)}, missing={sorted(registered - discovered)}"
        )
    return migrations, resource_root


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render(migrations: list[Migration]) -> bytes:
    chunks = [HEADER.encode("utf-8")]
    for migration in migrations:
        chunks.append(f"-- Migration V{migration.version}: {migration.name}\n".encode("utf-8"))
        chunks.append(migration.script)
        if not migration.script.endswith(b"\n"):
            chunks.append(b"\n")
        chunks.append(b"\n")
    chunks.append(b"-- Canonical migration metadata; applied_at is the documented V1.0 artifact constant.\n")
    for migration in migrations:
        statement = (
            "INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES "
            f"({migration.version}, {sql_literal(migration.name)}, {sql_literal(migration.checksum)}, 0);\n"
        )
        chunks.append(statement.encode("utf-8"))
    chunks.append(b"\nCOMMIT;\n")
    return b"".join(chunks)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the committed artifact matches the canonical registry/resources",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_args()
    migrations, resource_root = load_migrations(repository_root())
    artifact = resource_root / "haifa-agent-v1.0-init.sql"
    expected = render(migrations)
    if arguments.check:
        if not artifact.is_file() or artifact.read_bytes() != expected:
            print(f"OUT_OF_DATE: {artifact}", file=sys.stderr)
            return 1
        print(f"OK: {artifact} ({len(migrations)} migrations)")
        return 0
    artifact.write_bytes(expected)
    print(f"WROTE: {artifact} ({len(migrations)} migrations)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
