package io.haifa.agent.store.sqlite;

public enum SqliteStoreFailure {
    INVALID_CONFIGURATION,
    CONNECTION_FAILED,
    PRAGMA_VALIDATION_FAILED,
    MIGRATION_FAILED,
    MIGRATION_CHECKSUM_MISMATCH,
    TRANSACTION_FAILED,
    NO_ACTIVE_UNIT_OF_WORK,
    MAPPER_CONFIGURATION_FAILED
}
