package io.haifa.agent.project.filesystem;

public enum WorkspaceFileErrorCode {
    WORKSPACE_NOT_FOUND,
    WORKSPACE_INACTIVE,
    BINDING_NOT_FOUND,
    BINDING_INACTIVE,
    PERMISSION_DENIED,
    PATH_NOT_FOUND,
    PATH_ESCAPE,
    LINK_REJECTED,
    SENSITIVE_PATH,
    WRONG_FILE_TYPE,
    FILE_TOO_LARGE,
    LIST_BUDGET_EXCEEDED,
    BINARY_CONTENT,
    UNSUPPORTED_ENCODING,
    SEARCH_BUDGET_EXCEEDED,
    IO_FAILURE
}
