package io.haifa.agent.runtime.api;

public enum RuntimeErrorCode {
    RUN_NOT_FOUND,
    RUN_STATE_CONFLICT,
    RUN_VERSION_CONFLICT,
    IDEMPOTENCY_CONFLICT,
    INTERACTION_NOT_FOUND,
    INTERACTION_ALREADY_RESOLVED,
    INTERACTION_EXPIRED,
    INTERACTION_ACTION_NOT_ALLOWED,
    INTERACTION_REVISION_CONFLICT,
    APPROVAL_AUTHORITY_DENIED,
    APPROVAL_TARGET_STALE,
    CURSOR_INVALID,
    CURSOR_EXPIRED,
    CONTRACT_VERSION_UNSUPPORTED,
    PAYLOAD_TOO_LARGE,
    RATE_LIMITED,
    AUTHENTICATION_REQUIRED,
    INTERNAL_ERROR
}
