package io.haifa.agent.testing.suite;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.List;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/** Fail-closed summary of Maven Failsafe XML generated by one selected Critical Path case. */
public record MavenTestEvidence(
        int reportFiles, int tests, int failures, int errors, int skipped, List<Report> reports) {

    public enum Status {
        PASSED,
        FAILED,
        ERROR,
        SKIPPED,
        NOT_RUN,
        TIMEOUT
    }

    public record Report(String fileName, String sha256) {
        public Report {
            if (fileName == null || fileName.isBlank() || fileName.contains("/") || fileName.contains("\\")) {
                throw new IllegalArgumentException("report fileName must be a safe basename");
            }
            if (sha256 == null || !sha256.matches("[0-9a-f]{64}")) {
                throw new IllegalArgumentException("report sha256 must be lowercase hexadecimal");
            }
        }
    }

    public MavenTestEvidence {
        if (reportFiles < 0 || tests < 0 || failures < 0 || errors < 0 || skipped < 0) {
            throw new IllegalArgumentException("test evidence counters must not be negative");
        }
        reports = List.copyOf(reports);
        if (reportFiles != reports.size()) {
            throw new IllegalArgumentException("reportFiles must match reports size");
        }
    }

    public static MavenTestEvidence inspect(Path reportsDirectory)
            throws IOException, ParserConfigurationException, SAXException {
        if (!Files.isDirectory(reportsDirectory)) {
            return new MavenTestEvidence(0, 0, 0, 0, 0, List.of());
        }
        List<Path> reportPaths;
        try (var paths = Files.list(reportsDirectory)) {
            reportPaths = paths.filter(path -> Files.isRegularFile(path)
                            && path.getFileName().toString().startsWith("TEST-")
                            && path.getFileName().toString().endsWith(".xml"))
                    .sorted(Comparator.comparing(path -> path.getFileName().toString()))
                    .toList();
        }

        int tests = 0;
        int failures = 0;
        int errors = 0;
        int skipped = 0;
        List<Report> reports = new ArrayList<>();
        DocumentBuilderFactory factory = secureDocumentBuilderFactory();
        for (Path reportPath : reportPaths) {
            var builder = factory.newDocumentBuilder();
            builder.setErrorHandler(new DefaultHandler());
            Document document = builder.parse(reportPath.toFile());
            List<Element> suites = testSuites(document);
            if (suites.isEmpty()) {
                throw new SAXException("Failsafe report has no testsuite element");
            }
            for (Element suite : suites) {
                tests += nonNegativeInt(suite, "tests");
                failures += nonNegativeInt(suite, "failures");
                errors += nonNegativeInt(suite, "errors");
                skipped += nonNegativeInt(suite, "skipped");
            }
            reports.add(new Report(reportPath.getFileName().toString(), sha256(reportPath)));
        }
        return new MavenTestEvidence(reportPaths.size(), tests, failures, errors, skipped, reports);
    }

    public static void deleteRawReports(Path reportsDirectory) throws IOException {
        if (!Files.exists(reportsDirectory)) {
            return;
        }
        try (var paths = Files.walk(reportsDirectory)) {
            for (Path path : paths.sorted(Comparator.reverseOrder()).toList()) {
                Files.delete(path);
            }
        }
    }

    public boolean passing() {
        return reportFiles > 0 && tests > 0 && failures == 0 && errors == 0 && skipped == 0;
    }

    public Status status(boolean completed, int exitCode, boolean readable) {
        if (!completed) {
            return Status.TIMEOUT;
        }
        if (exitCode != 0 || failures > 0 || errors > 0) {
            return Status.FAILED;
        }
        if (!readable) {
            return Status.ERROR;
        }
        if (reportFiles == 0 || tests == 0) {
            return Status.NOT_RUN;
        }
        if (skipped > 0) {
            return Status.SKIPPED;
        }
        return Status.PASSED;
    }

    private static List<Element> testSuites(Document document) {
        Element root = document.getDocumentElement();
        if (root != null && "testsuite".equals(root.getTagName())) {
            return List.of(root);
        }
        NodeList nodes = document.getElementsByTagName("testsuite");
        List<Element> suites = new ArrayList<>(nodes.getLength());
        for (int index = 0; index < nodes.getLength(); index++) {
            suites.add((Element) nodes.item(index));
        }
        return suites;
    }

    private static int nonNegativeInt(Element suite, String attribute) throws SAXException {
        String value = suite.getAttribute(attribute);
        if (value.isBlank()) {
            return 0;
        }
        try {
            int parsed = Integer.parseInt(value);
            if (parsed < 0) {
                throw new SAXException("negative testsuite attribute: " + attribute);
            }
            return parsed;
        } catch (NumberFormatException exception) {
            throw new SAXException("invalid testsuite attribute: " + attribute, exception);
        }
    }

    private static DocumentBuilderFactory secureDocumentBuilderFactory() throws ParserConfigurationException {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
        factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
        factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
        factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
        factory.setXIncludeAware(false);
        factory.setExpandEntityReferences(false);
        return factory;
    }

    private static String sha256(Path path) throws IOException {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            try (var input = Files.newInputStream(path)) {
                byte[] buffer = new byte[8192];
                int read;
                while ((read = input.read(buffer)) >= 0) {
                    if (read > 0) digest.update(buffer, 0, read);
                }
            }
            return HexFormat.of().formatHex(digest.digest());
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 is unavailable", exception);
        }
    }
}
