-- Generated by build-support/scripts/generate_haifa_agent_v1_schema.py.
-- Do not edit this artifact directly; edit the canonical migration registry/resources.
PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;

CREATE TABLE IF NOT EXISTS schema_migration (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    checksum TEXT NOT NULL,
    applied_at INTEGER NOT NULL CHECK (applied_at >= 0)
);

-- Migration V1: runtime_store
-- Haifa Agent Runtime Store V1. UTC instants are epoch milliseconds.
-- Every encoded BLOB has an adjacent schema version and SHA-256 column.

CREATE TABLE session (
    session_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    owner_principal_id TEXT NOT NULL,
    owner_principal_type TEXT NOT NULL,
    project_id TEXT,
    scope TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    closed_at INTEGER,
    version INTEGER NOT NULL CHECK (version >= 0),
    metadata_schema_version TEXT NOT NULL,
    metadata_payload BLOB NOT NULL,
    metadata_hash TEXT NOT NULL,
    CHECK (closed_at IS NULL OR closed_at >= created_at)
) STRICT;

CREATE INDEX idx_session_tenant_owner
ON session(tenant_id, owner_principal_id);

CREATE TABLE configuration_snapshot (
    configuration_ref TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    definition_id TEXT NOT NULL,
    definition_version TEXT NOT NULL,
    profile_id TEXT NOT NULL,
    profile_version TEXT NOT NULL,
    run_type TEXT NOT NULL,
    content_schema_version TEXT NOT NULL,
    content_payload BLOB NOT NULL,
    content_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0)
) STRICT;

CREATE TABLE run (
    run_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    root_run_id TEXT NOT NULL,
    parent_run_id TEXT,
    session_id TEXT NOT NULL,
    project_id TEXT,
    tenant_id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    principal_type TEXT NOT NULL,
    agent_definition_id TEXT NOT NULL,
    agent_definition_version TEXT NOT NULL,
    product_profile_id TEXT NOT NULL,
    product_profile_version TEXT NOT NULL,
    run_type TEXT NOT NULL,
    invocation_mode TEXT NOT NULL,
    depth INTEGER NOT NULL CHECK (depth >= 0),
    objective TEXT NOT NULL,
    budget_max_input_tokens INTEGER NOT NULL CHECK (budget_max_input_tokens >= 0),
    budget_max_output_tokens INTEGER NOT NULL CHECK (budget_max_output_tokens >= 0),
    budget_max_cached_input_tokens INTEGER NOT NULL CHECK (budget_max_cached_input_tokens >= 0),
    budget_max_tool_calls INTEGER NOT NULL CHECK (budget_max_tool_calls >= 0),
    budget_max_model_calls INTEGER NOT NULL CHECK (budget_max_model_calls >= 0),
    budget_max_child_runs INTEGER NOT NULL CHECK (budget_max_child_runs >= 0),
    budget_max_cost_currency TEXT NOT NULL,
    budget_max_cost_minor_units INTEGER NOT NULL CHECK (budget_max_cost_minor_units >= 0),
    limit_max_iterations INTEGER NOT NULL CHECK (limit_max_iterations > 0),
    limit_max_depth INTEGER NOT NULL CHECK (limit_max_depth >= 0),
    limit_max_parallel_children INTEGER NOT NULL CHECK (limit_max_parallel_children > 0),
    limit_max_wall_time_millis INTEGER NOT NULL CHECK (limit_max_wall_time_millis > 0),
    limit_max_idle_time_millis INTEGER NOT NULL CHECK (limit_max_idle_time_millis > 0),
    configuration_ref TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN (
        'PENDING', 'QUEUED', 'RUNNING', 'SUSPENDING', 'SUSPENDED',
        'WAITING_INTERACTION', 'WAITING_APPROVAL', 'COMPLETING',
        'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT'
    )),
    usage_input_tokens INTEGER NOT NULL CHECK (usage_input_tokens >= 0),
    usage_output_tokens INTEGER NOT NULL CHECK (usage_output_tokens >= 0),
    usage_cached_input_tokens INTEGER NOT NULL CHECK (usage_cached_input_tokens >= 0),
    usage_model_calls INTEGER NOT NULL CHECK (usage_model_calls >= 0),
    usage_tool_calls INTEGER NOT NULL CHECK (usage_tool_calls >= 0),
    usage_child_runs INTEGER NOT NULL CHECK (usage_child_runs >= 0),
    usage_cost_minor_units INTEGER NOT NULL CHECK (usage_cost_minor_units >= 0),
    usage_wall_time_millis INTEGER NOT NULL CHECK (usage_wall_time_millis >= 0),
    result_schema_version TEXT,
    result_payload BLOB,
    result_hash TEXT,
    error_schema_version TEXT,
    error_payload BLOB,
    error_hash TEXT,
    waiting_request_id TEXT,
    termination_reason TEXT,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    queued_at INTEGER,
    started_at INTEGER,
    suspended_at INTEGER,
    resumed_at INTEGER,
    completed_at INTEGER,
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    version INTEGER NOT NULL CHECK (version >= 0),
    FOREIGN KEY (session_id) REFERENCES session(session_id),
    FOREIGN KEY (configuration_ref) REFERENCES configuration_snapshot(configuration_ref),
    FOREIGN KEY (root_run_id) REFERENCES run(run_id),
    FOREIGN KEY (parent_run_id) REFERENCES run(run_id),
    CHECK ((result_payload IS NULL) = (result_schema_version IS NULL)),
    CHECK ((result_payload IS NULL) = (result_hash IS NULL)),
    CHECK ((error_payload IS NULL) = (error_schema_version IS NULL)),
    CHECK ((error_payload IS NULL) = (error_hash IS NULL))
) STRICT;

CREATE INDEX idx_run_session_created
ON run(session_id, created_at);

CREATE INDEX idx_run_status_updated
ON run(status, updated_at);

CREATE TABLE execution_attempt (
    attempt_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    run_id TEXT NOT NULL,
    attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
    status TEXT NOT NULL CHECK (status IN (
        'QUEUED', 'RUNNING', 'SUCCEEDED', 'PAUSED', 'CANCELLED', 'FAILED', 'ABANDONED'
    )),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    started_at INTEGER,
    heartbeat_at INTEGER,
    completed_at INTEGER,
    worker_id TEXT,
    resumed_from_checkpoint_id TEXT,
    error_schema_version TEXT,
    error_payload BLOB,
    error_hash TEXT,
    version INTEGER NOT NULL CHECK (version >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    FOREIGN KEY (resumed_from_checkpoint_id) REFERENCES checkpoint(checkpoint_id),
    UNIQUE (run_id, attempt_number),
    CHECK ((error_payload IS NULL) = (error_schema_version IS NULL)),
    CHECK ((error_payload IS NULL) = (error_hash IS NULL))
) STRICT;

CREATE UNIQUE INDEX uq_active_attempt_per_run
ON execution_attempt(run_id)
WHERE status IN ('QUEUED', 'RUNNING');

CREATE INDEX idx_attempt_run_number
ON execution_attempt(run_id, attempt_number);

CREATE TABLE session_message (
    message_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    run_id TEXT,
    parent_message_id TEXT,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    role TEXT NOT NULL CHECK (role IN (
        'SYSTEM', 'DEVELOPER', 'USER', 'ASSISTANT', 'TOOL', 'AGENT', 'RUNTIME'
    )),
    status TEXT NOT NULL CHECK (status IN (
        'CREATED', 'STREAMING', 'COMPLETED', 'FAILED', 'REDACTED', 'DELETED'
    )),
    visibility TEXT NOT NULL CHECK (visibility IN (
        'USER_VISIBLE', 'AGENT_VISIBLE', 'ADMIN_VISIBLE', 'INTERNAL', 'HIDDEN', 'REDACTED'
    )),
    content_schema_version TEXT NOT NULL,
    content_payload BLOB NOT NULL,
    content_hash TEXT NOT NULL,
    metadata_schema_version TEXT NOT NULL,
    metadata_payload BLOB NOT NULL,
    metadata_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    FOREIGN KEY (session_id) REFERENCES session(session_id),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    FOREIGN KEY (parent_message_id) REFERENCES session_message(message_id),
    UNIQUE (session_id, sequence)
) STRICT;

CREATE INDEX idx_message_run_sequence
ON session_message(run_id, sequence);

CREATE TABLE step (
    step_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    run_id TEXT NOT NULL,
    parent_step_id TEXT,
    branch_id TEXT,
    type TEXT NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    status TEXT NOT NULL CHECK (status IN (
        'PENDING', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED', 'SKIPPED'
    )),
    result_schema_version TEXT,
    result_payload BLOB,
    result_hash TEXT,
    error_schema_version TEXT,
    error_payload BLOB,
    error_hash TEXT,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    started_at INTEGER,
    completed_at INTEGER,
    version INTEGER NOT NULL CHECK (version >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    FOREIGN KEY (parent_step_id) REFERENCES step(step_id),
    UNIQUE (run_id, sequence),
    CHECK ((result_payload IS NULL) = (result_schema_version IS NULL)),
    CHECK ((result_payload IS NULL) = (result_hash IS NULL)),
    CHECK ((error_payload IS NULL) = (error_schema_version IS NULL)),
    CHECK ((error_payload IS NULL) = (error_hash IS NULL))
) STRICT;

CREATE TABLE tool_call (
    tool_call_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    run_id TEXT NOT NULL,
    step_id TEXT NOT NULL,
    provider_correlation_id TEXT,
    idempotency_key TEXT,
    tool_name TEXT NOT NULL,
    tool_version TEXT NOT NULL,
    arguments_schema_version TEXT NOT NULL,
    arguments_payload BLOB NOT NULL,
    arguments_hash TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN (
        'REQUESTED', 'VALIDATING', 'POLICY_CHECK', 'WAITING_APPROVAL', 'APPROVED',
        'RUNNING', 'COMPLETED', 'FAILED', 'DENIED', 'CANCELLED', 'TIMEOUT'
    )),
    result_schema_version TEXT,
    result_payload BLOB,
    result_hash TEXT,
    error_schema_version TEXT,
    error_payload BLOB,
    error_hash TEXT,
    requested_at INTEGER NOT NULL CHECK (requested_at >= 0),
    started_at INTEGER,
    completed_at INTEGER,
    version INTEGER NOT NULL CHECK (version >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    FOREIGN KEY (step_id) REFERENCES step(step_id),
    UNIQUE (run_id, idempotency_key),
    CHECK ((result_payload IS NULL) = (result_schema_version IS NULL)),
    CHECK ((result_payload IS NULL) = (result_hash IS NULL)),
    CHECK ((error_payload IS NULL) = (error_schema_version IS NULL)),
    CHECK ((error_payload IS NULL) = (error_hash IS NULL))
) STRICT;

CREATE INDEX idx_tool_call_run_requested
ON tool_call(run_id, requested_at);

CREATE TABLE plan (
    plan_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    run_id TEXT NOT NULL UNIQUE,
    objective TEXT NOT NULL,
    items_schema_version TEXT NOT NULL,
    items_payload BLOB NOT NULL,
    items_hash TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision >= 0),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    FOREIGN KEY (run_id) REFERENCES run(run_id)
) STRICT;

CREATE TABLE run_output (
    run_id TEXT PRIMARY KEY,
    output_schema_version TEXT NOT NULL,
    output_payload BLOB NOT NULL,
    output_hash TEXT NOT NULL,
    updated_at INTEGER NOT NULL CHECK (updated_at >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id)
) STRICT;

CREATE TABLE checkpoint (
    checkpoint_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    step_id TEXT,
    type TEXT NOT NULL CHECK (type IN (
        'AUTOMATIC', 'MANUAL', 'INTERACTION', 'APPROVAL',
        'FAILURE_RECOVERY', 'GRAPH_NODE', 'WORKSPACE_SNAPSHOT'
    )),
    status TEXT NOT NULL CHECK (status IN ('CREATED', 'VERIFIED', 'CORRUPTED')),
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    payload_store_type TEXT NOT NULL,
    payload_location TEXT NOT NULL,
    payload_schema_id TEXT NOT NULL,
    payload_schema_version TEXT NOT NULL,
    state_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    FOREIGN KEY (step_id) REFERENCES step(step_id),
    UNIQUE (run_id, sequence)
) STRICT;

CREATE TABLE checkpoint_payload (
    checkpoint_id TEXT PRIMARY KEY,
    state_schema_version TEXT NOT NULL,
    state_payload BLOB NOT NULL,
    state_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    FOREIGN KEY (checkpoint_id) REFERENCES checkpoint(checkpoint_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE runtime_event (
    event_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    type TEXT NOT NULL,
    data_schema_version TEXT NOT NULL,
    data_payload BLOB NOT NULL,
    data_hash TEXT NOT NULL,
    occurred_at INTEGER NOT NULL CHECK (occurred_at >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    UNIQUE (run_id, sequence)
) STRICT;

CREATE INDEX idx_event_run_occurred
ON runtime_event(run_id, occurred_at);

CREATE TABLE outbox (
    event_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    type TEXT NOT NULL,
    payload_schema_version TEXT NOT NULL,
    payload BLOB NOT NULL,
    payload_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    published_at INTEGER,
    FOREIGN KEY (event_id) REFERENCES runtime_event(event_id),
    FOREIGN KEY (run_id, sequence) REFERENCES runtime_event(run_id, sequence),
    UNIQUE (run_id, sequence)
) STRICT;

CREATE INDEX idx_outbox_pending
ON outbox(published_at, created_at, event_id);

CREATE TABLE outbox_consumer (
    consumer_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    consumed_at INTEGER NOT NULL CHECK (consumed_at >= 0),
    PRIMARY KEY (consumer_id, event_id),
    FOREIGN KEY (event_id) REFERENCES outbox(event_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE idempotency (
    caller_scope TEXT NOT NULL,
    operation TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    run_id TEXT,
    command_applied INTEGER NOT NULL DEFAULT 0 CHECK (command_applied IN (0, 1)),
    result_schema_version TEXT,
    result_payload BLOB,
    result_hash TEXT,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    PRIMARY KEY (caller_scope, operation, idempotency_key),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    CHECK ((result_payload IS NULL) = (result_schema_version IS NULL)),
    CHECK ((result_payload IS NULL) = (result_hash IS NULL))
) STRICT;

CREATE TABLE memory_selection (
    run_id TEXT PRIMARY KEY,
    retrieval_policy_version TEXT NOT NULL,
    query_digest TEXT NOT NULL,
    memories_schema_version TEXT NOT NULL,
    memories_payload BLOB NOT NULL,
    memories_hash TEXT NOT NULL,
    updated_at INTEGER NOT NULL CHECK (updated_at >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id)
) STRICT;

CREATE TABLE model_continuation (
    continuation_id TEXT PRIMARY KEY,
    continuation_version TEXT NOT NULL,
    continuation_digest TEXT NOT NULL,
    byte_length INTEGER NOT NULL CHECK (byte_length > 0),
    assistant_message_id TEXT NOT NULL UNIQUE,
    run_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    model_call_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    configuration_digest TEXT NOT NULL,
    tool_correlations_schema_version TEXT NOT NULL,
    tool_correlations_payload BLOB NOT NULL,
    tool_correlations_hash TEXT NOT NULL,
    protection_version TEXT NOT NULL,
    nonce_schema_version TEXT NOT NULL,
    nonce_payload BLOB NOT NULL,
    nonce_hash TEXT NOT NULL,
    ciphertext_schema_version TEXT NOT NULL,
    ciphertext_payload BLOB NOT NULL,
    ciphertext_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    FOREIGN KEY (assistant_message_id) REFERENCES session_message(message_id),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    FOREIGN KEY (session_id) REFERENCES session(session_id)
) STRICT;

CREATE TABLE skill_activation (
    run_id TEXT NOT NULL,
    skill_alias TEXT NOT NULL,
    coordinate TEXT NOT NULL,
    content_digest TEXT NOT NULL,
    reason TEXT NOT NULL,
    requested_by TEXT NOT NULL,
    instruction_bytes INTEGER NOT NULL CHECK (instruction_bytes > 0),
    estimated_tokens INTEGER NOT NULL CHECK (estimated_tokens > 0),
    activation_schema_version TEXT NOT NULL,
    activation_payload BLOB NOT NULL,
    activation_hash TEXT NOT NULL,
    activated_at INTEGER NOT NULL CHECK (activated_at >= 0),
    PRIMARY KEY (run_id, skill_alias),
    FOREIGN KEY (run_id) REFERENCES run(run_id)
) STRICT;

CREATE TABLE skill_resource_usage (
    run_id TEXT PRIMARY KEY,
    bytes_read INTEGER NOT NULL CHECK (bytes_read >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id)
) STRICT;

CREATE TABLE conversation_summary (
    summary_id TEXT NOT NULL,
    summary_version INTEGER NOT NULL CHECK (summary_version > 0),
    session_id TEXT NOT NULL,
    covered_from INTEGER NOT NULL CHECK (covered_from > 0),
    covered_through INTEGER NOT NULL CHECK (covered_through >= covered_from),
    source_hash TEXT NOT NULL,
    content_schema_version TEXT NOT NULL,
    content_payload BLOB NOT NULL,
    content_hash TEXT NOT NULL,
    estimated_tokens INTEGER NOT NULL CHECK (estimated_tokens > 0),
    policy_version TEXT NOT NULL,
    compressor_version TEXT NOT NULL,
    valid INTEGER NOT NULL CHECK (valid IN (0, 1)),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    PRIMARY KEY (summary_id, summary_version),
    FOREIGN KEY (session_id) REFERENCES session(session_id),
    UNIQUE (session_id, summary_version)
) STRICT;

CREATE INDEX idx_summary_latest_valid
ON conversation_summary(session_id, valid, summary_version DESC);

CREATE TABLE tool_result_asset (
    asset_ref TEXT PRIMARY KEY,
    tool_call_id TEXT NOT NULL,
    result_schema_version TEXT NOT NULL,
    result_payload BLOB NOT NULL,
    result_hash TEXT NOT NULL,
    byte_length INTEGER NOT NULL CHECK (byte_length > 0),
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    FOREIGN KEY (tool_call_id) REFERENCES tool_call(tool_call_id)
) STRICT;

CREATE TABLE tool_journal (
    run_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    state TEXT NOT NULL CHECK (state IN (
        'INTENT_RECORDED', 'DISPATCHED', 'ACKNOWLEDGED', 'PENDING_RESULT',
        'COMPLETED', 'FAILED', 'OUTCOME_UNKNOWN'
    )),
    tool_idempotency TEXT NOT NULL CHECK (tool_idempotency IN (
        'PURE', 'IDEMPOTENT', 'IDEMPOTENT_WITH_KEY', 'NON_IDEMPOTENT', 'UNKNOWN'
    )),
    result_schema_version TEXT,
    result_payload BLOB,
    result_hash TEXT,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    updated_at INTEGER NOT NULL CHECK (updated_at >= created_at),
    PRIMARY KEY (run_id, idempotency_key),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    CHECK ((result_payload IS NULL) = (result_schema_version IS NULL)),
    CHECK ((result_payload IS NULL) = (result_hash IS NULL))
) STRICT;

CREATE INDEX idx_tool_journal_uncertain
ON tool_journal(run_id, state);

CREATE TABLE interaction_request (
    request_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    principal_type TEXT NOT NULL,
    type TEXT NOT NULL,
    prompt TEXT NOT NULL,
    approval INTEGER NOT NULL CHECK (approval IN (0, 1)),
    target_type TEXT NOT NULL,
    target_schema_version TEXT NOT NULL,
    target_payload BLOB NOT NULL,
    target_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    expires_at INTEGER NOT NULL CHECK (expires_at > created_at),
    FOREIGN KEY (run_id) REFERENCES run(run_id)
) STRICT;

CREATE INDEX idx_interaction_request_pending
ON interaction_request(run_id, expires_at, created_at);

CREATE TABLE interaction_response (
    response_id TEXT PRIMARY KEY,
    request_id TEXT NOT NULL UNIQUE,
    run_id TEXT NOT NULL,
    response_type TEXT NOT NULL CHECK (response_type IN ('APPROVE', 'REJECT', 'CLARIFY')),
    inputs_schema_version TEXT NOT NULL,
    inputs_payload BLOB NOT NULL,
    inputs_hash TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    responded_at INTEGER NOT NULL CHECK (responded_at >= 0),
    resolved_at INTEGER NOT NULL CHECK (resolved_at >= responded_at),
    FOREIGN KEY (request_id) REFERENCES interaction_request(request_id),
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    UNIQUE (run_id, idempotency_key)
) STRICT;

CREATE TABLE interaction_application (
    request_id TEXT PRIMARY KEY,
    resolution_applied INTEGER NOT NULL DEFAULT 0 CHECK (resolution_applied IN (0, 1)),
    applied_at INTEGER,
    FOREIGN KEY (request_id) REFERENCES interaction_request(request_id) ON DELETE CASCADE,
    CHECK ((resolution_applied = 0 AND applied_at IS NULL)
        OR (resolution_applied = 1 AND applied_at IS NOT NULL))
) STRICT;

-- Migration V2: lossless_runtime_fields
ALTER TABLE run ADD COLUMN waiting_request_type TEXT;
ALTER TABLE run ADD COLUMN termination_description TEXT;
ALTER TABLE configuration_snapshot ADD COLUMN content_payload_hash TEXT;
ALTER TABLE checkpoint_payload ADD COLUMN payload_hash TEXT;

-- Migration V4: interaction_event_journal
-- Task 02: stable Runtime Journal identity/range reads and durable HITL/Steer state.
-- The clean baseline applies this after V1-V2; version 3 is intentionally absent.

ALTER TABLE runtime_event ADD COLUMN event_schema_version TEXT NOT NULL DEFAULT '1';
ALTER TABLE runtime_event ADD COLUMN correlation_id TEXT;
ALTER TABLE runtime_event ADD COLUMN causation_id TEXT;

CREATE INDEX idx_runtime_event_run_sequence
ON runtime_event(run_id, sequence);

CREATE TABLE runtime_event_stream (
    run_id TEXT PRIMARY KEY,
    head_sequence INTEGER NOT NULL CHECK (head_sequence >= 0),
    earliest_sequence INTEGER NOT NULL CHECK (earliest_sequence >= 1),
    updated_at INTEGER NOT NULL CHECK (updated_at >= 0),
    FOREIGN KEY (run_id) REFERENCES run(run_id) ON DELETE CASCADE,
    CHECK (earliest_sequence <= head_sequence + 1)
) STRICT;

INSERT INTO runtime_event_stream(run_id, head_sequence, earliest_sequence, updated_at)
SELECT run_id, MAX(sequence), MIN(sequence), MAX(occurred_at)
FROM runtime_event
GROUP BY run_id;

ALTER TABLE interaction_request ADD COLUMN revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0);
ALTER TABLE interaction_request ADD COLUMN kind TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE interaction_request ADD COLUMN state TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (state IN ('PENDING', 'RESPONDED', 'APPLIED', 'EXPIRED', 'CANCELLED', 'INVALIDATED'));
ALTER TABLE interaction_request ADD COLUMN expiration_outcome TEXT NOT NULL DEFAULT 'FAIL_RUN'
    CHECK (expiration_outcome IN ('FAIL_RUN', 'CANCEL_RUN', 'RETURN_TO_AGENT'));
ALTER TABLE interaction_request ADD COLUMN state_reason_code TEXT;
ALTER TABLE interaction_request ADD COLUMN state_changed_at INTEGER;

UPDATE interaction_request
SET kind = CASE
        WHEN approval = 1 THEN 'approval'
        WHEN type IN ('clarification', 'confirmation', 'selection', 'input-required',
                      'artifact-review', 'conflict-resolution') THEN type
        ELSE 'unknown'
    END,
    expiration_outcome = CASE WHEN approval = 1 THEN 'CANCEL_RUN' ELSE 'FAIL_RUN' END,
    state = CASE
        WHEN EXISTS (
            SELECT 1 FROM interaction_application application
            WHERE application.request_id = interaction_request.request_id
              AND application.resolution_applied = 1
        ) THEN 'APPLIED'
        WHEN EXISTS (
            SELECT 1 FROM interaction_response response
            WHERE response.request_id = interaction_request.request_id
        ) THEN 'RESPONDED'
        ELSE 'PENDING'
    END,
    revision = CASE
        WHEN EXISTS (
            SELECT 1 FROM interaction_application application
            WHERE application.request_id = interaction_request.request_id
              AND application.resolution_applied = 1
        ) THEN 2
        WHEN EXISTS (
            SELECT 1 FROM interaction_response response
            WHERE response.request_id = interaction_request.request_id
        ) THEN 1
        ELSE 0
    END,
    state_changed_at = COALESCE(
        (SELECT application.applied_at FROM interaction_application application
         WHERE application.request_id = interaction_request.request_id
           AND application.resolution_applied = 1),
        (SELECT response.resolved_at FROM interaction_response response
         WHERE response.request_id = interaction_request.request_id)
    );

-- V1 permitted more than one unresolved request for a Run. Retain the newest and
-- invalidate older requests deterministically before adding the authoritative constraint.
UPDATE interaction_request
SET state = 'INVALIDATED',
    revision = revision + 1,
    state_reason_code = 'MIGRATION_SUPERSEDED_PENDING',
    state_changed_at = created_at
WHERE state = 'PENDING'
  AND EXISTS (
      SELECT 1
      FROM interaction_request newer
      WHERE newer.run_id = interaction_request.run_id
        AND newer.state = 'PENDING'
        AND (
            newer.created_at > interaction_request.created_at
            OR (newer.created_at = interaction_request.created_at
                AND newer.request_id > interaction_request.request_id)
        )
  );

CREATE UNIQUE INDEX uq_interaction_pending_per_run
ON interaction_request(run_id)
WHERE state = 'PENDING';

CREATE INDEX idx_interaction_due
ON interaction_request(state, expires_at, request_id);

ALTER TABLE interaction_response ADD COLUMN action TEXT NOT NULL DEFAULT 'submit';
ALTER TABLE interaction_response ADD COLUMN expected_revision INTEGER NOT NULL DEFAULT 0 CHECK (expected_revision >= 0);
ALTER TABLE interaction_response ADD COLUMN caller_scope TEXT NOT NULL DEFAULT '';
ALTER TABLE interaction_response ADD COLUMN canonical_digest TEXT NOT NULL DEFAULT '';
ALTER TABLE interaction_response ADD COLUMN responder_tenant_id TEXT NOT NULL DEFAULT '';
ALTER TABLE interaction_response ADD COLUMN responder_principal_id TEXT NOT NULL DEFAULT '';
ALTER TABLE interaction_response ADD COLUMN responder_principal_type TEXT NOT NULL DEFAULT '';
ALTER TABLE interaction_response ADD COLUMN receipt_status TEXT NOT NULL DEFAULT 'ACCEPTED'
    CHECK (receipt_status IN ('ACCEPTED', 'DUPLICATE', 'APPLIED'));

UPDATE interaction_response
SET action = CASE response_type
        WHEN 'APPROVE' THEN 'approve'
        WHEN 'REJECT' THEN 'reject'
        ELSE 'submit'
    END,
    caller_scope = (
        SELECT request.tenant_id || '|' || request.principal_type || '|' || request.principal_id
        FROM interaction_request request
        WHERE request.request_id = interaction_response.request_id
    ),
    responder_tenant_id = (
        SELECT request.tenant_id FROM interaction_request request
        WHERE request.request_id = interaction_response.request_id
    ),
    responder_principal_id = (
        SELECT request.principal_id FROM interaction_request request
        WHERE request.request_id = interaction_response.request_id
    ),
    responder_principal_type = (
        SELECT request.principal_type FROM interaction_request request
        WHERE request.request_id = interaction_response.request_id
    );

CREATE UNIQUE INDEX uq_interaction_response_idempotency
ON interaction_response(caller_scope, request_id, idempotency_key);

CREATE TABLE run_input (
    input_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    expected_run_version INTEGER,
    contents_schema_version TEXT NOT NULL,
    contents_payload BLOB NOT NULL,
    contents_hash TEXT NOT NULL,
    caller_scope TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    canonical_digest TEXT NOT NULL CHECK (length(canonical_digest) = 64),
    submitted_at INTEGER NOT NULL CHECK (submitted_at >= 0),
    accepted_at INTEGER NOT NULL CHECK (accepted_at >= submitted_at),
    status TEXT NOT NULL CHECK (status IN ('ACCEPTED', 'APPLIED', 'REJECTED')),
    applied_at INTEGER,
    attempt_id TEXT,
    iteration INTEGER,
    reason_code TEXT,
    FOREIGN KEY (run_id) REFERENCES run(run_id),
    FOREIGN KEY (attempt_id) REFERENCES execution_attempt(attempt_id),
    UNIQUE (caller_scope, run_id, idempotency_key),
    CHECK (expected_run_version IS NULL OR expected_run_version >= 0),
    CHECK (iteration IS NULL OR iteration >= 0),
    CHECK (
        (status = 'ACCEPTED' AND applied_at IS NULL AND attempt_id IS NULL AND iteration IS NULL)
        OR
        (status = 'APPLIED' AND applied_at IS NOT NULL AND attempt_id IS NOT NULL AND iteration IS NOT NULL)
        OR
        (status = 'REJECTED' AND reason_code IS NOT NULL)
    )
) STRICT;

CREATE INDEX idx_run_input_pending
ON run_input(run_id, status, accepted_at, input_id);

ALTER TABLE idempotency ADD COLUMN target_type TEXT;
ALTER TABLE idempotency ADD COLUMN target_id TEXT;
ALTER TABLE idempotency ADD COLUMN request_digest TEXT;
ALTER TABLE idempotency ADD COLUMN expires_at INTEGER;

-- Migration V5: sdk_conversation
-- Product-neutral Conversation Session index and command idempotency bindings.
-- Message bodies remain authoritative in the Runtime session_message table.

CREATE TABLE sdk_conversation (
    session_id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    principal_type TEXT NOT NULL,
    display_name TEXT NOT NULL CHECK (length(display_name) BETWEEN 1 AND 256),
    status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    active_run_id TEXT,
    active_run_version INTEGER,
    active_dispatch_key TEXT,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    last_activity_at INTEGER NOT NULL CHECK (last_activity_at >= created_at),
    revision INTEGER NOT NULL CHECK (revision >= 0),
    FOREIGN KEY (session_id) REFERENCES session(session_id),
    CHECK ((active_run_id IS NULL) = (active_run_version IS NULL)),
    CHECK (active_run_id IS NULL OR active_dispatch_key IS NULL)
) STRICT;

CREATE INDEX idx_sdk_conversation_scope_activity
ON sdk_conversation(
    tenant_id,
    principal_id,
    principal_type,
    status,
    last_activity_at DESC,
    session_id DESC
);

CREATE TABLE sdk_conversation_command (
    dispatch_key TEXT PRIMARY KEY,
    caller_scope_digest TEXT NOT NULL,
    operation TEXT NOT NULL,
    idempotency_key_digest TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    session_id TEXT NOT NULL,
    run_id TEXT,
    completed INTEGER NOT NULL CHECK (completed IN (0, 1)),
    result_revision INTEGER,
    created_at INTEGER NOT NULL CHECK (created_at >= 0),
    CHECK ((completed = 1) = (result_revision IS NOT NULL)),
    UNIQUE (caller_scope_digest, operation, idempotency_key_digest)
) STRICT;

CREATE INDEX idx_sdk_conversation_command_session
ON sdk_conversation_command(session_id, created_at);

-- Migration V6: memory_foundation
CREATE TABLE memory_candidate (
    candidate_id TEXT PRIMARY KEY NOT NULL,
    request_key_digest TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    visibility TEXT NOT NULL,
    security_label_bits INTEGER NOT NULL,
    kind TEXT NOT NULL,
    subject_key TEXT NOT NULL,
    normalized_digest TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    revision INTEGER NOT NULL CHECK (revision >= 0),
    updated_at INTEGER NOT NULL,
    payload_schema_version INTEGER NOT NULL CHECK (payload_schema_version = 1),
    payload_type TEXT NOT NULL CHECK (payload_type = 'memory-candidate'),
    payload_hash TEXT NOT NULL,
    payload BLOB NOT NULL,
    UNIQUE (tenant_id, owner_id, scope_type, target_id, visibility, request_key_digest)
) STRICT;

CREATE INDEX idx_memory_candidate_scope_page
    ON memory_candidate(tenant_id, owner_id, scope_type, target_id, visibility, updated_at DESC, candidate_id DESC);
CREATE INDEX idx_memory_candidate_pending_subject
    ON memory_candidate(
        tenant_id, owner_id, scope_type, target_id, visibility, kind, normalized_digest, subject_key)
    WHERE status = 'PENDING';

CREATE TABLE memory_record (
    memory_id TEXT NOT NULL,
    memory_version INTEGER NOT NULL CHECK (memory_version > 0),
    tenant_id TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    visibility TEXT NOT NULL,
    security_label_bits INTEGER NOT NULL,
    kind TEXT NOT NULL,
    subject_key TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'INVALIDATED')),
    normalized_digest TEXT NOT NULL,
    updated_at INTEGER NOT NULL,
    payload_schema_version INTEGER NOT NULL CHECK (payload_schema_version = 1),
    payload_type TEXT NOT NULL CHECK (payload_type = 'memory-record'),
    payload_hash TEXT NOT NULL,
    payload BLOB NOT NULL,
    PRIMARY KEY (memory_id, memory_version)
) STRICT;

CREATE UNIQUE INDEX uq_memory_record_active_id
    ON memory_record(memory_id) WHERE status = 'ACTIVE';
CREATE UNIQUE INDEX uq_memory_record_active_subject
    ON memory_record(tenant_id, owner_id, scope_type, target_id, visibility, kind, subject_key)
    WHERE status = 'ACTIVE';
CREATE INDEX idx_memory_record_scope_page
    ON memory_record(tenant_id, owner_id, scope_type, target_id, visibility, updated_at DESC, memory_id DESC, memory_version DESC);

CREATE TABLE memory_audit_event (
    event_id INTEGER PRIMARY KEY AUTOINCREMENT,
    operation TEXT NOT NULL,
    candidate_id TEXT,
    memory_id TEXT,
    memory_version INTEGER,
    tenant_id TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    visibility TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    safe_attributes_json TEXT NOT NULL,
    occurred_at INTEGER NOT NULL,
    idempotency_key_digest TEXT,
    request_digest TEXT,
    candidate_revision INTEGER,
    CHECK ((idempotency_key_digest IS NULL) = (request_digest IS NULL))
) STRICT;

CREATE UNIQUE INDEX uq_memory_audit_idempotency
    ON memory_audit_event(
        tenant_id, owner_id, scope_type, target_id, visibility, operation, idempotency_key_digest)
    WHERE idempotency_key_digest IS NOT NULL;
CREATE INDEX idx_memory_audit_scope_time
    ON memory_audit_event(tenant_id, owner_id, scope_type, target_id, visibility, occurred_at);

-- Migration V7: artifact_foundation
CREATE TABLE artifact (
    artifact_id TEXT NOT NULL,
    artifact_version INTEGER NOT NULL,
    artifact_type TEXT NOT NULL,
    title TEXT NOT NULL,
    payload_id TEXT NOT NULL,
    payload_sha256 TEXT NOT NULL,
    payload_byte_count INTEGER NOT NULL,
    payload_media_type TEXT NOT NULL,
    project_id TEXT NOT NULL,
    workspace_ref TEXT NOT NULL,
    run_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    file_change_set_ref TEXT,
    execution_ref TEXT,
    source_logical_path TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    export_policy TEXT NOT NULL,
    created_by_id TEXT NOT NULL,
    created_by_type TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at_ms INTEGER NOT NULL,
    PRIMARY KEY(artifact_id, artifact_version),
    UNIQUE(payload_id),
    CHECK(artifact_version >= 1),
    CHECK(payload_byte_count >= 0),
    CHECK(status IN ('PUBLISHED','REVOKED'))
);
CREATE INDEX ix_artifact_project_created ON artifact(project_id, created_at_ms, artifact_id);

-- Migration V8: tool_reconciliation_evidence
ALTER TABLE tool_journal ADD COLUMN dispatch_execution_id TEXT;
ALTER TABLE tool_journal ADD COLUMN dispatch_process_id INTEGER;
ALTER TABLE tool_journal ADD COLUMN dispatch_workdir_digest TEXT;
ALTER TABLE tool_journal ADD COLUMN reconcile_status TEXT;
ALTER TABLE tool_journal ADD COLUMN reconcile_reason TEXT;

CREATE INDEX idx_tool_journal_dispatch_execution
ON tool_journal(dispatch_execution_id)
WHERE dispatch_execution_id IS NOT NULL;

-- Migration V9: optional_interaction_expiry
-- Human interactions may remain pending until answered or explicitly cancelled.
-- Existing requests retain their configured deadline.

DROP INDEX idx_interaction_request_pending;
DROP INDEX idx_interaction_due;

ALTER TABLE interaction_request ADD COLUMN expires_at_v9 INTEGER
    CHECK (expires_at_v9 IS NULL OR expires_at_v9 > created_at);
UPDATE interaction_request SET expires_at_v9 = expires_at;
ALTER TABLE interaction_request DROP COLUMN expires_at;
ALTER TABLE interaction_request RENAME COLUMN expires_at_v9 TO expires_at;

CREATE INDEX idx_interaction_request_pending
ON interaction_request(run_id, expires_at, created_at);

CREATE INDEX idx_interaction_due
ON interaction_request(state, expires_at, request_id)
WHERE expires_at IS NOT NULL;

-- Migration V10: human_wait_timing
ALTER TABLE run
ADD COLUMN accumulated_human_wait_millis INTEGER NOT NULL DEFAULT 0
CHECK (accumulated_human_wait_millis >= 0);

ALTER TABLE run
ADD COLUMN human_wait_started_at INTEGER
CHECK (human_wait_started_at IS NULL OR human_wait_started_at >= created_at);

-- Older schemas did not record when a human wait began. Start accounting from
-- migration time without inventing an unverified historical paused duration.
UPDATE run
SET human_wait_started_at = updated_at
WHERE status IN ('WAITING_INTERACTION', 'WAITING_APPROVAL');

-- Migration V11: separate_run_limits
ALTER TABLE run
ADD COLUMN limit_max_tool_calls INTEGER NOT NULL DEFAULT 0
CHECK (limit_max_tool_calls >= 0);

ALTER TABLE run
ADD COLUMN limit_max_model_calls INTEGER NOT NULL DEFAULT 1
CHECK (limit_max_model_calls > 0);

ALTER TABLE run
ADD COLUMN limit_max_child_runs INTEGER NOT NULL DEFAULT 0
CHECK (limit_max_child_runs >= 0);

-- Before this migration, the three budget columns also stored the corresponding
-- run limits. Preserve those limits and recover the real frozen budget values
-- from the content-addressed configuration snapshot.
UPDATE run
SET limit_max_tool_calls = budget_max_tool_calls,
    limit_max_model_calls = budget_max_model_calls,
    limit_max_child_runs = budget_max_child_runs,
    budget_max_tool_calls = COALESCE(
        (SELECT CAST(json_extract(CAST(content_payload AS TEXT), '$.budget.maxToolCalls') AS INTEGER)
         FROM configuration_snapshot
         WHERE configuration_ref = run.configuration_ref),
        budget_max_tool_calls),
    budget_max_model_calls = COALESCE(
        (SELECT CAST(json_extract(CAST(content_payload AS TEXT), '$.budget.maxModelCalls') AS INTEGER)
         FROM configuration_snapshot
         WHERE configuration_ref = run.configuration_ref),
        budget_max_model_calls),
    budget_max_child_runs = COALESCE(
        (SELECT CAST(json_extract(CAST(content_payload AS TEXT), '$.budget.maxChildRuns') AS INTEGER)
         FROM configuration_snapshot
         WHERE configuration_ref = run.configuration_ref),
        budget_max_child_runs);

-- Migration V1000: project_product_session
CREATE TABLE project_product_session (
    session_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    project_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    principal_type TEXT NOT NULL,
    configuration_id TEXT NOT NULL,
    configuration_version TEXT NOT NULL,
    configuration_digest TEXT NOT NULL,
    product_profile_ref TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES session(session_id) ON DELETE CASCADE
);

CREATE INDEX idx_project_product_session_project
    ON project_product_session(project_id, session_id);

-- Migration V1001: coding_session_product_loop
CREATE TABLE coding_session_activity (
    session_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    project_id TEXT NOT NULL,
    tenant_id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    principal_type TEXT NOT NULL,
    display_name TEXT NOT NULL,
    active_run_id TEXT,
    active_run_version INTEGER,
    active_dispatch_key TEXT,
    created_at_ms INTEGER NOT NULL,
    last_activity_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL,
    CHECK ((active_run_id IS NULL) = (active_run_version IS NULL)),
    FOREIGN KEY (session_id) REFERENCES project_product_session(session_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_coding_session_active_dispatch
    ON coding_session_activity(active_dispatch_key)
    WHERE active_dispatch_key IS NOT NULL;

CREATE INDEX idx_coding_session_scope_activity
    ON coding_session_activity(
        tenant_id, principal_id, principal_type, project_id, last_activity_at_ms DESC, session_id DESC
    );

CREATE TABLE coding_session_command (
    caller_scope_digest TEXT NOT NULL,
    operation TEXT NOT NULL,
    idempotency_key_digest TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    dispatch_key TEXT NOT NULL UNIQUE,
    session_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    content_nonce BLOB NOT NULL,
    content_ciphertext BLOB NOT NULL,
    content_digest TEXT NOT NULL,
    run_id TEXT,
    created_at_ms INTEGER NOT NULL,
    PRIMARY KEY (caller_scope_digest, operation, idempotency_key_digest)
);

CREATE TABLE coding_follow_up (
    follow_up_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL,
    session_id TEXT NOT NULL,
    bound_run_id TEXT NOT NULL,
    content_nonce BLOB NOT NULL,
    content_ciphertext BLOB NOT NULL,
    content_digest TEXT NOT NULL,
    idempotency_key_digest TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    dispatch_key TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    sequence_no INTEGER NOT NULL,
    dispatched_run_id TEXT,
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL,
    claimed_at_ms INTEGER,
    restored_at_ms INTEGER,
    revision INTEGER NOT NULL,
    UNIQUE (session_id, idempotency_key_digest),
    UNIQUE (session_id, sequence_no),
    CHECK (status IN ('PENDING', 'CLAIMED', 'DISPATCHED', 'RESTORED')),
    CHECK ((status = 'DISPATCHED') = (dispatched_run_id IS NOT NULL)),
    FOREIGN KEY (session_id) REFERENCES coding_session_activity(session_id) ON DELETE CASCADE
);

CREATE INDEX idx_coding_follow_up_dispatch
    ON coding_follow_up(session_id, status, sequence_no);

-- Migration V1002: coding_session_event_cursor
CREATE TABLE coding_session_event_cursor (
    session_id TEXT PRIMARY KEY NOT NULL,
    run_id TEXT NOT NULL,
    feed_version TEXT NOT NULL,
    exclusive_sequence INTEGER NOT NULL CHECK (exclusive_sequence > 0),
    updated_at_ms INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES project_product_session(session_id)
);

CREATE INDEX idx_coding_session_event_cursor_run
    ON coding_session_event_cursor(run_id, exclusive_sequence);

-- Migration V1003: coding_session_management
ALTER TABLE coding_session_activity
    ADD COLUMN session_status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (session_status IN ('ACTIVE', 'ARCHIVED', 'CLOSED', 'DELETED'));

CREATE INDEX idx_coding_session_scope_status_activity
    ON coding_session_activity(
        tenant_id, principal_id, principal_type, project_id, session_status,
        last_activity_at_ms DESC, session_id DESC
    );

-- Migration V1004: coding_session_model_preference
CREATE TABLE coding_session_model_preference (
    session_id TEXT PRIMARY KEY NOT NULL,
    schema_version TEXT NOT NULL,
    model_id TEXT NOT NULL,
    revision INTEGER NOT NULL,
    idempotency_key_digest TEXT,
    request_digest TEXT,
    updated_at_ms INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES project_product_session(session_id) ON DELETE CASCADE,
    CHECK (revision >= 0),
    CHECK ((idempotency_key_digest IS NULL) = (request_digest IS NULL))
);

-- Migration V1005: coding_delivery_intent
ALTER TABLE coding_session_command
    ADD COLUMN delivery_intent TEXT NOT NULL DEFAULT 'WORKTREE_ONLY'
    CHECK (delivery_intent IN ('WORKTREE_ONLY', 'LOCAL_COMMIT', 'REMOTE_PUSH', 'PULL_REQUEST'));

CREATE INDEX idx_coding_session_command_run
    ON coding_session_command(run_id)
    WHERE run_id IS NOT NULL;

CREATE INDEX idx_coding_session_command_pending
    ON coding_session_command(session_id, created_at_ms DESC)
    WHERE run_id IS NULL;

-- Migration V1006: coding_follow_up_dispatched_run_index
CREATE INDEX idx_coding_follow_up_dispatched_run
    ON coding_follow_up(dispatched_run_id)
    WHERE dispatched_run_id IS NOT NULL;

-- Migration V1007: coding_workspace_registry
CREATE TABLE coding_workspace_registry (
    project_id TEXT NOT NULL,
    workspace_ref TEXT NOT NULL,
    location_ref TEXT NOT NULL,
    safe_display_name TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('INITIAL', 'APPROVED_ATTACH', 'APPROVED_WORKTREE_CREATE')),
    status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'DISABLED', 'REVOKED')),
    location_nonce BLOB NOT NULL,
    location_ciphertext BLOB NOT NULL,
    location_digest TEXT NOT NULL,
    physical_fingerprint TEXT NOT NULL,
    created_at_ms INTEGER NOT NULL,
    validated_at_ms INTEGER NOT NULL,
    revoked_at_ms INTEGER,
    revocation_reason_code TEXT,
    version INTEGER NOT NULL CHECK (version >= 0),
    PRIMARY KEY (project_id, workspace_ref),
    UNIQUE (project_id, location_ref),
    CHECK ((status = 'ACTIVE' AND revoked_at_ms IS NULL AND revocation_reason_code IS NULL)
        OR (status != 'ACTIVE' AND revoked_at_ms IS NOT NULL AND revocation_reason_code IS NOT NULL))
);

CREATE INDEX idx_coding_workspace_registry_project_status
    ON coding_workspace_registry(project_id, status, workspace_ref);

CREATE TABLE coding_workspace_access (
    tenant_id TEXT NOT NULL,
    principal_type TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('READ', 'DEVELOP')),
    PRIMARY KEY (tenant_id, principal_type, principal_id, workspace_id)
);

-- Canonical migration metadata; applied_at is the documented V1.0 artifact constant.
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1, 'runtime_store', 'sha256:e7c83a55486c9e383a1e6a7aa9a1959090292e50418d926275745698d9ea56c1', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (2, 'lossless_runtime_fields', 'sha256:19e472624d42dc74745ad14f531d2915a3476e992e98ff741bc06a372580ea83', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (4, 'interaction_event_journal', 'sha256:5fa1634298f7d3f1903db7ef3c943f4357d3ede9fe719eb7df01ca95fa3defde', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (5, 'sdk_conversation', 'sha256:06850f037485f4e7f31f7b5cd9d2b1e05586e00f02cc2cc0d1148811989234bb', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (6, 'memory_foundation', 'sha256:e414529b92bb6adf84d9fdb00ae2921b01caa70d8bd0c1ff2fdd50c2d7735d2b', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (7, 'artifact_foundation', 'sha256:c806063b8379d2fd28ef80715738c8f614a1d475637a80fa79126cb8d0157354', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (8, 'tool_reconciliation_evidence', 'sha256:9d6eedef3e025900bf300f6a791d23a3ea1744e06b839689b875d01728f2cba5', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (9, 'optional_interaction_expiry', 'sha256:ddfb9b697b8e7744beeff4905b6639fc7949308c958059f162d9f87ee258033b', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (10, 'human_wait_timing', 'sha256:2a556ed9bc06d467975ba34b146dc3afe90fa63cd6b1e1577ea53311bc54f9b2', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (11, 'separate_run_limits', 'sha256:ace3fa99a7b762fd58cc6bc9274660effd851d31007b9eea1f24dce9818cf4e2', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1000, 'project_product_session', 'sha256:929d869e45117a3e829be4f9b995bc646874583410c6f3572800f264aa4f418b', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1001, 'coding_session_product_loop', 'sha256:109f86f30032eecb16a6d34ab945ce4fba8573eed8d8391f800d7132f2f06fcf', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1002, 'coding_session_event_cursor', 'sha256:f566cba113dcf3ab9eb6f0883497e672cf3d02c5d7a3d64e94d5f186ed89c2b6', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1003, 'coding_session_management', 'sha256:76a3afa2dbc7c146899146bd3aada25ba7402943e5196958d4690c413281dded', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1004, 'coding_session_model_preference', 'sha256:847529404d60be37de66abd65d08f68d3fc188baafeaf448561e8e6fb54840c5', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1005, 'coding_delivery_intent', 'sha256:c9b8955eb79faa6a45d825b43b852bcd7a7483219bafc6a4fec0cb116021ac58', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1006, 'coding_follow_up_dispatched_run_index', 'sha256:3e9897383621e181c925df9a61600e7bd37e867e389b41a633fa849e5d2a5ce2', 0);
INSERT INTO schema_migration(version, name, checksum, applied_at) VALUES (1007, 'coding_workspace_registry', 'sha256:240073f28a76ed93943bd329dc7bf06d3133422c6e656aa46111ea4a8dbcf879', 0);

COMMIT;
