CREATE TABLE artifact (
    artifact_id TEXT NOT NULL,
    artifact_version INTEGER NOT NULL,
    artifact_type TEXT NOT NULL,
    title TEXT NOT NULL,
    payload_id TEXT NOT NULL,
    payload_sha256 TEXT NOT NULL,
    payload_byte_count INTEGER NOT NULL,
    payload_media_type TEXT NOT NULL,
    project_id TEXT NOT NULL,
    workspace_ref TEXT NOT NULL,
    run_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    file_change_set_ref TEXT,
    execution_ref TEXT,
    source_logical_path TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    export_policy TEXT NOT NULL,
    created_by_id TEXT NOT NULL,
    created_by_type TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at_ms INTEGER NOT NULL,
    PRIMARY KEY(artifact_id, artifact_version),
    UNIQUE(payload_id),
    CHECK(artifact_version >= 1),
    CHECK(payload_byte_count >= 0),
    CHECK(status IN ('PUBLISHED','REVOKED'))
);
CREATE INDEX ix_artifact_project_created ON artifact(project_id, created_at_ms, artifact_id);
