package io.haifa.agent.model.api;

public enum ModelParameterResolutionFailure {
    PROFILE_UNAVAILABLE,
    PROFILE_STALE,
    BINDING_MISMATCH,
    REASONING_MODE_UNSUPPORTED,
    REASONING_EFFORT_REQUIRED,
    REASONING_EFFORT_UNSUPPORTED,
    REASONING_BUDGET_UNSUPPORTED,
    OUTPUT_LIMIT_UNSUPPORTED
}
