package io.haifa.agent.orchestration.api;

public enum WorkflowErrorCode {
    INVALID_DEFINITION,
    UNSUPPORTED_CAPABILITY,
    DEFINITION_NOT_FOUND,
    RUN_NOT_FOUND,
    INVALID_STATE,
    ITERATION_LIMIT_EXCEEDED,
    STATE_MERGE_CONFLICT,
    NODE_EXECUTION_FAILED,
    OUTCOME_UNKNOWN,
    INVALID_RESUME,
    IDEMPOTENCY_CONFLICT,
    PERSISTENCE_CONFLICT,
    BINDING_MISMATCH,
    CODEC_MISMATCH,
    TIMED_OUT,
    TERMINAL_RUN
}
